[build]
  publish = "."

# Security and Performance Headers
[[headers]]
  for = "/*"
  [headers.values]
    # Security Headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Content Security Policy - Allow CDN sources for JOSE library
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdn.skypack.dev https://cdn.jsdelivr.net https://unpkg.com; style-src 'self' 'unsafe-inline'; connect-src 'self' https://cdn.skypack.dev https://cdn.jsdelivr.net https://unpkg.com; font-src 'self'; img-src 'self' data:;"
    
    # Performance Headers
    Cache-Control = "public, max-age=31536000, immutable"
    
    # Additional Security
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Permissions-Policy = "geolocation=(), camera=(), microphone=()"

# Cache static assets
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

# Handle SPA routing (if needed in future)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}

# Remove the old API redirect as this is a client-side only app